# Use the official .NET SDK image as the base image
FROM mcr.microsoft.com/dotnet/sdk:7.0

# Install OpenJDK 11
RUN apt-get update && \
    apt-get install -y openjdk-11-jdk && \
    apt-get clean

# Install dotnet-sonarscanner
RUN dotnet tool install --global dotnet-sonarscanner

# Add .NET global tools to PATH
ENV PATH="${PATH}:/root/.dotnet/tools"

# docker build -f .\docker\Dockerfile.sonar -t dotnet-sdk-sonarscanner .